name: max_alpha_mobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^10.0.0
  webview_flutter: ^4.13.0
  serious_python: ^4.5.1
  http: ^1.2.0
  cupertino_icons: ^1.0.8

dependency_overrides:
  serious_python_android:
    path: plugins/serious_python_android_stub

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dashboard_v5_bot2.html
